use_frameworks!

target 'RippleEffectView_Example' do
  pod 'RippleEffectView', :path => '../'

  target 'RippleEffectView_Tests' do
    inherit! :search_paths

  pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'FBSnapshotTestCase', '~> 2.1.4'
  pod 'Nimble-Snapshots', '~> 4.4.0'
  end
end
