use_frameworks!

target 'RippleEffectView_Example' do
  pod 'RippleEffectView', :path => '../'

  target 'RippleEffectView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
